[08-Aug-25 14:14:25 - WARNING] - bot - Could not get info for channel -1002099922815: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.45 thinks: The channel parameter is invalid
[08-Aug-25 14:14:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:14:28 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:16:53 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 14:16:55 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 14:19:03 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:19:03 - INFO] - bot - Bot stopped.
[08-Aug-25 14:19:08 - WARNING] - bot - Could not get info for channel -1002099922815: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.45 thinks: The channel parameter is invalid
[08-Aug-25 14:19:10 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:19:10 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:21:37 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:21:37 - INFO] - bot - Bot stopped.
[08-Aug-25 14:21:43 - WARNING] - bot - Could not get info for channel 1002051400881: Peer id invalid: 1002051400881
[08-Aug-25 14:21:43 - WARNING] - bot - Could not get info for channel 1002099922815: Peer id invalid: 1002099922815
[08-Aug-25 14:21:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:21:45 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:22:08 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:22:08 - INFO] - bot - Bot stopped.
[08-Aug-25 14:22:16 - WARNING] - bot - Could not get info for channel -1002099922815: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.45 thinks: The channel parameter is invalid
[08-Aug-25 14:22:18 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:22:18 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:22:58 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:22:58 - INFO] - bot - Bot stopped.
[08-Aug-25 14:23:15 - WARNING] - bot - Could not get info for channel -1002099922815: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.45 thinks: The channel parameter is invalid
[08-Aug-25 14:23:17 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:23:17 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:23:31 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:23:31 - INFO] - bot - Bot stopped.
[08-Aug-25 14:23:38 - WARNING] - bot - Could not get info for channel 1002099922815: Peer id invalid: 1002099922815
[08-Aug-25 14:23:39 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:23:39 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:24:04 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:24:04 - INFO] - bot - Bot stopped.
[08-Aug-25 14:26:26 - WARNING] - bot - Could not get info for channel -1002099922815: Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.45 thinks: The channel parameter is invalid
[08-Aug-25 14:26:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:26:28 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:26:44 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:26:44 - INFO] - bot - Bot stopped.
[08-Aug-25 14:26:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:26:58 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:32:28 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:32:28 - INFO] - bot - Bot stopped.
[08-Aug-25 14:49:06 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:49:06 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 14:56:06 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 14:56:06 - INFO] - bot - Bot stopped.
[08-Aug-25 14:56:15 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 14:56:15 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:00:52 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:00:52 - INFO] - bot - Bot stopped.
[08-Aug-25 15:02:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:02:51 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:09:11 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:09:11 - INFO] - bot - Bot stopped.
[08-Aug-25 15:09:19 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:09:19 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:12:14 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:12:14 - INFO] - bot - Bot stopped.
[08-Aug-25 15:13:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:13:45 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:18:11 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:18:11 - INFO] - bot - Bot stopped.
[08-Aug-25 15:18:17 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:18:17 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:18:55 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:18:55 - INFO] - bot - Bot stopped.
[08-Aug-25 15:19:01 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:19:01 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:20:05 - WARNING] - pyrogram.types.messages_and_media.message - Empty messages cannot be copied.
[08-Aug-25 15:20:06 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:20:10 - WARNING] - pyrogram.types.messages_and_media.message - Empty messages cannot be copied.
[08-Aug-25 15:20:10 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:21:39 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:21:39 - INFO] - bot - Bot stopped.
[08-Aug-25 15:21:45 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:21:45 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:21:45 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:21:45 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:21:48 - ERROR] - pyrogram.dispatcher - Failed to decode "None". The value does not represent an existing local file, HTTP URL, or valid file id.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/utils.py", line 60, in get_input_media_from_file_id
    decoded = FileId.decode(file_id)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/file_id.py", line 216, in decode
    file_type, dc_id = struct.unpack("<ii", buffer.read(8))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 8 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 189, in start_handler
    await message.reply_photo(photo=Config.START_PIC, caption=caption, reply_markup=buttons, quote=True)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 2943, in reply_photo
    return await self._client.send_photo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_photo.py", line 223, in send_photo
    media = utils.get_input_media_from_file_id(photo, FileType.PHOTO, ttl_seconds=(1 << 31) - 1 if view_once else ttl_seconds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/utils.py", line 62, in get_input_media_from_file_id
    raise ValueError(
ValueError: Failed to decode "None". The value does not represent an existing local file, HTTP URL, or valid file id.
[08-Aug-25 15:21:50 - ERROR] - pyrogram.dispatcher - Failed to decode "None". The value does not represent an existing local file, HTTP URL, or valid file id.
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/utils.py", line 60, in get_input_media_from_file_id
    decoded = FileId.decode(file_id)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/file_id.py", line 216, in decode
    file_type, dc_id = struct.unpack("<ii", buffer.read(8))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 8 bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 189, in start_handler
    await message.reply_photo(photo=Config.START_PIC, caption=caption, reply_markup=buttons, quote=True)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 2943, in reply_photo
    return await self._client.send_photo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_photo.py", line 223, in send_photo
    media = utils.get_input_media_from_file_id(photo, FileType.PHOTO, ttl_seconds=(1 << 31) - 1 if view_once else ttl_seconds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/utils.py", line 62, in get_input_media_from_file_id
    raise ValueError(
ValueError: Failed to decode "None". The value does not represent an existing local file, HTTP URL, or valid file id.
[08-Aug-25 15:22:49 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:22:49 - INFO] - bot - Bot stopped.
[08-Aug-25 15:22:58 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:22:58 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:22:58 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:22:58 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:26:21 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:26:21 - INFO] - bot - Bot stopped.
[08-Aug-25 15:26:28 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:26:28 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:26:28 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:26:28 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:29:20 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:29:29 - WARNING] - bot - Telegram says: [400 CHANNEL_INVALID] (caused by "channels.GetChannels") Pyrogram 2.3.45 thinks: The channel parameter is invalid
[08-Aug-25 15:29:29 - WARNING] - bot - Make Sure bot is Admin in DB Channel, and Double check the CHANNEL_ID Value, Current Value -1001555535698
[08-Aug-25 15:29:29 - INFO] - bot - 
Bot Stopped. Join https://t.me/ps_discuss for support
[08-Aug-25 15:30:26 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:30:26 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:31:26 - WARNING] - pyrogram.types.messages_and_media.message - Empty messages cannot be copied.
[08-Aug-25 15:31:26 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:35:35 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:35:35 - INFO] - bot - Bot stopped.
[08-Aug-25 15:35:42 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:35:42 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:35:42 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:36:44 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:36:44 - INFO] - bot - Bot stopped.
[08-Aug-25 15:36:51 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:36:51 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:36:51 - INFO] - apscheduler.scheduler - Added job "ScheduleManager.delete_messages" to job store "default"
[08-Aug-25 15:40:01 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:40:21 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:41:26 - INFO] - apscheduler.scheduler - Removed job 1861045099_48_1754667086.646664
[08-Aug-25 15:41:26 - INFO] - apscheduler.executors.default - Running job "ScheduleManager.delete_messages (trigger: date[2025-08-08 15:41:26 UTC], next run at: 2025-08-08 15:41:26 UTC)" (scheduled at 2025-08-08 15:41:26.646636+00:00)
[08-Aug-25 15:41:26 - INFO] - apscheduler.executors.default - Job "ScheduleManager.delete_messages (trigger: date[2025-08-08 15:41:26 UTC], next run at: 2025-08-08 15:41:26 UTC)" executed successfully
[08-Aug-25 15:41:31 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:42:23 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:42:23 - INFO] - bot - Bot stopped.
[08-Aug-25 15:42:29 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:42:29 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:42:36 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:42:38 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:51:59 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:51:59 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:52:03 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:52:05 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:53:02 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:53:24 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:55:48 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 15:55:48 - INFO] - bot - Bot stopped.
[08-Aug-25 15:55:54 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 15:55:54 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 15:56:53 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 15:56:56 - ERROR] - pyrogram.dispatcher - Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
Traceback (most recent call last):
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/dispatcher.py", line 363, in handler_worker
    await handler.callback(self.client, *args)
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/handlers/message_handler.py", line 154, in resolve_future_or_callback
    await self.original_callback(client, message, *args)
  File "/home/runner/workspace/bot/plugins/start_handler.py", line 23, in start_handler
    if await handle_force_sub(client, message):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/bot/utils/subscription.py", line 67, in handle_force_sub
    await message.reply(
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/types/messages_and_media/message.py", line 1482, in reply_text
    return await self._client.send_message(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/messages/send_message.py", line 200, in send_message
    r = await self.invoke(rpc)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/methods/advanced/invoke.py", line 80, in invoke
    r = await self.session.invoke(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 420, in invoke
    return await self.send(query, timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/session/session.py", line 377, in send
    RPCError.raise_it(result, type(data))
  File "/home/runner/workspace/.pythonlibs/lib/python3.12/site-packages/pyrogram/errors/rpc_error.py", line 93, in raise_it
    raise getattr(
pyrogram.errors.exceptions.bad_request_400.ReplyMarkupInvalid: Telegram says: [400 REPLY_MARKUP_INVALID] (caused by "messages.SendMessage") Pyrogram 2.3.45 thinks: The provided reply markup is invalid
[08-Aug-25 16:09:16 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 16:09:16 - INFO] - bot - Bot stopped.
[08-Aug-25 16:09:22 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 16:09:22 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 16:13:31 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 16:13:31 - INFO] - bot - Bot stopped.
[08-Aug-25 16:13:37 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 16:13:37 - INFO] - apscheduler.scheduler - Scheduler started
[08-Aug-25 16:17:21 - INFO] - root - Stop signal received (SIGTERM). Exiting...
[08-Aug-25 16:17:21 - INFO] - bot - Bot stopped.
[08-Aug-25 16:17:27 - INFO] - bot - Bot Running..!

Created by 
https://t.me/ps_updates
[08-Aug-25 16:17:27 - INFO] - apscheduler.scheduler - Scheduler started
